create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  dia date not null,
  hora_entrada time without time zone not null,
  hora_salida time without time zone null,
  run text not null,
  dv text not null,
  carrera text not null,
  sede text not null,
  anio_ingreso integer not null,
  actividad text not null,
  tematica text not null,
  observaciones text not null,
  espacio text not null,
  estado text not null,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

create index if not exists attendance_records_dia_idx on public.attendance_records (dia);
create index if not exists attendance_records_run_dia_idx on public.attendance_records (run, dia);
