create table if not exists public.attendance_records (
  id bigint generated by default as identity primary key,
  dia date not null,
  hora_entrada timestamptz,
  hora_salida timestamptz,
  run text not null,
  dv text not null,
  carrera text,
  sede text not null,
  anio_ingreso integer,
  actividad text,
  tematica text,
  observaciones text,
  espacio text,
  estado text not null,
  created_at timestamptz not null default now()
);

create index if not exists attendance_records_dia_idx
  on public.attendance_records (dia);

create index if not exists attendance_records_run_dia_idx
  on public.attendance_records (run, dia);
